name: flutter_native_boost
description: Flutter和Native页面混合栈管理
version: 1.0.2
homepage: https://github.com/bozaigao/flutter_native_boost

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  g_json: ^4.0.0-nullsafety.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.2.0

flutter:
  plugin:
    platforms:
      android:
        package: net.medlinker.flutter_native_boost
        pluginClass: FNBoostPlugin
      ios:
        pluginClass: FNBoostPlugin
